[cubi.tools]
pid = "https://github.com/core-unit-bioinformatics/cubi-tools"
version = "prototype"

[[cubi.tools.script]]
name = "update_metadata.py"
version = "0.1.0"

[cubi.metadata]
pid = "https://github.com/core-unit-bioinformatics/template-metadata-files"
version = "1.5.0"

[tool.black]
line-length = 88

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.messages_control]
disable=[
  "logging-fstring-interpolation",
  "useless-return",
  "missing-module-docstring"
]

[tool.isort]
profile = "black"
